plugins {
    id 'com.android.application'
}

android {
    namespace 'com.frinsecta.gbfcache'
    compileSdk 33

    defaultConfig {
        applicationId 'com.frinsecta.gbfcache'
        minSdk 24
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly files('libs/api-82.jar')
}