plugins {
    id 'com.android.application'
}

android {
    namespace 'com.frinsecta.gbfcache'
    compileSdk 34

    defaultConfig {
        applicationId 'com.frinsecta.gbfcache'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '0.1.102'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packaging {
        resources {
            // 确保 META-INF/xposed 下的文件不会被误合并或剔除
            merges += []
            excludes += []
        }
    }

    lint {
        abortOnError false
    }
}

dependencies {
    compileOnly("io.github.libxposed:api:102.0.0")
}